version: '2'
services:
  db:
    build: ./postgres-1c/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--locale=ru_RU.UTF-8 --lc-messages=C            
  pgstudio:
    image: lukasmartinelli/pgstudio
    ports:
      - "8081:8080"        
  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - "8082:5050"      
  powa-web:
    build: ./powa-web
    ports:
      - "8083:8888"
  pgbadger:
    build: ./pgbadger    
    volumes_from: 
      - db:ro
    depends_on:
      - db
    ports:
      - "8084:80"
  index:
    image: busybox
    volumes:
      - ./www:/www
    ports:
      - "8080:80"
    command: httpd -f -v -h /www
  
